spring:
  profiles:
    active: dev

  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true




server:
    tomcat:
      uri-encoding: UTF-8
